# Generated by Django 4.0.6 on 2022-07-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebg',
            name='name1',
            field=models.CharField(max_length=100, null=True, verbose_name='BG name1'),
        ),
        migrations.AlterField(
            model_name='homebg',
            name='name2',
            field=models.CharField(max_length=100, null=True, verbose_name='BG name2'),
        ),
    ]
