# Generated by Django 4.0.6 on 2022-07-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_homebg_name1_alter_homebg_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, null=True, verbose_name='HomeSite name1')),
                ('name2', models.CharField(max_length=100, null=True, verbose_name='HomeSite name2')),
                ('about', models.TextField(null=True, verbose_name='HomeSite')),
            ],
            options={
                'verbose_name': 'HomeSite',
                'verbose_name_plural': 'HomesSite',
            },
        ),
        migrations.DeleteModel(
            name='HomeBG',
        ),
    ]
