# Generated by Django 4.0.6 on 2022-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_homesite_delete_homebg'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='AboutWeb name1')),
                ('name2', models.CharField(max_length=100, verbose_name='AboutWeb name2')),
                ('name3', models.CharField(max_length=100, verbose_name='AboutWeb name4')),
                ('about1', models.TextField(verbose_name='AboutWeb')),
                ('about2', models.TextField(verbose_name='AboutWeb')),
                ('about3', models.TextField(verbose_name='AboutWeb')),
                ('about4', models.TextField(verbose_name='AboutWeb')),
            ],
        ),
    ]
