# Generated by Django 4.0.6 on 2022-07-06 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_aboutweb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutweb',
            options={'verbose_name': 'AboutWeb', 'verbose_name_plural': 'AboutWebs'},
        ),
    ]
