# Generated by Django 4.0.6 on 2022-07-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_aboutweb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutweb',
            name='name3',
            field=models.CharField(max_length=100, null=True, verbose_name='AboutWeb name3'),
        ),
    ]
