# Generated by Django 4.0.6 on 2022-07-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_aboutweb_name3'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutweb',
            name='img',
            field=models.ImageField(null=True, upload_to='media', verbose_name='AboutWeb image'),
        ),
    ]
