# Generated by Django 4.0.6 on 2022-07-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_aboutweb_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='FashionBlog name1')),
                ('name2', models.CharField(max_length=100, verbose_name='FashionBlog name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='FashionBlog image')),
                ('about1', models.TextField(verbose_name='FashionBlog')),
                ('about2', models.TextField(verbose_name='FashionBlog')),
            ],
            options={
                'verbose_name': 'FashionBlog',
                'verbose_name_plural': 'FashionBlogs',
            },
        ),
    ]
