# Generated by Django 4.0.6 on 2022-07-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_fashionblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='WorkBlog name1')),
                ('name2', models.CharField(max_length=100, verbose_name='WorkBlog name2')),
                ('img', models.ImageField(upload_to='media', verbose_name='WorkBlog image')),
                ('about', models.TextField(verbose_name='WorkBlog')),
            ],
            options={
                'verbose_name': 'WorkBlog',
                'verbose_name_plural': 'WorkBlogs',
            },
        ),
    ]
