# Generated by Django 4.0.6 on 2022-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_workblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesite',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='homesite',
            name='name2',
        ),
        migrations.AddField(
            model_name='homesite',
            name='contact',
            field=models.CharField(max_length=100, null=True, verbose_name='HomeSite contact'),
        ),
        migrations.AddField(
            model_name='homesite',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='HomeSite name'),
        ),
        migrations.AddField(
            model_name='homesite',
            name='video',
            field=models.TextField(null=True, verbose_name='HomeSite video link'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='about',
            field=models.TextField(null=True, verbose_name='HomeSite about'),
        ),
    ]
