# Generated by Django 4.0.6 on 2022-07-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_homesite_name1_remove_homesite_name2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesite',
            options={'verbose_name': 'HomeSite', 'verbose_name_plural': 'HomeSites'},
        ),
        migrations.AlterField(
            model_name='homesite',
            name='contact',
            field=models.CharField(max_length=30, null=True, verbose_name='HomeSite contact'),
        ),
        migrations.AlterField(
            model_name='homesite',
            name='video',
            field=models.TextField(null=True, verbose_name='Homesite video link'),
        ),
    ]
