# Generated by Django 4.0.6 on 2022-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_homesite_options_alter_homesite_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutWeb1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='AboutWeb1 name')),
                ('about', models.TextField(null=True, verbose_name='AboutWeb1')),
            ],
            options={
                'verbose_name': 'AboutWeb1',
                'verbose_name_plural': 'AboutWebs1',
            },
        ),
        migrations.DeleteModel(
            name='AboutWeb',
        ),
    ]
